version: 0.2

phases:
  pre_build:
    commands:
      - echo Install Helm S3
      - curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - helm plugin install https://github.com/hypnoglow/helm-s3.git
  build:
    commands:
      - echo Push to S3
      - helm s3 init ${S3_CHARTS_URL}
      - helm repo add temp ${S3_CHARTS_URL}
      - helm package /home/ec2-user/fleetman -d /home/ec2-user/
      - helm s3 push --relative /home/ec2-user/fleetman-0.1.0.tgz fleetman
  post_build:
    commands:
      - echo Build completed on `date`
